IMAGE_CORPUS_PATH: "data/coco/" 
INDEX_PATH: "faiss/coco/openai/clip-vit-base-patch32/image_index.faiss"

VLM_MODEL_FAMILY: "clip" 
VLM_MODEL_NAME: "openai/clip-vit-base-patch32"
IMG_SIZE: 224
PATCH_SIZE: 32

SHOW_IMAGE_GALLERY: True
SHOW_ANNOTATORS: True

TOP_K: 5

RETRIEVAL_LOGS_PATH: "logs/retrieval_logs.json"